// <auto-generated />
namespace PVIMS.Entities.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddConditionLabs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddConditionLabs));
        
        string IMigrationMetadata.Id
        {
            get { return "201601131119390_Add Condition Labs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
