// <auto-generated />
namespace PVIMS.Entities.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDatasetMapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDatasetMapping));
        
        string IMigrationMetadata.Id
        {
            get { return "201705031320389_AddDatasetMapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
