// <auto-generated />
namespace PVIMS.Entities.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCurrentStatusToActivityInstance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCurrentStatusToActivityInstance));
        
        string IMigrationMetadata.Id
        {
            get { return "201711281930496_AddCurrentStatusToActivityInstance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
