// <auto-generated />
namespace PVIMS.Entities.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddActionNameToMetaForm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddActionNameToMetaForm));
        
        string IMigrationMetadata.Id
        {
            get { return "202003191551557_AddActionNameToMetaForm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
